FROM python

COPY ./main_process/requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY main_process ./main_process

WORKDIR ./main_process

CMD ["python" , "-u", "./main_process.py"]