FROM python

COPY ./main_process/requirements.txt ./requirements.txt

RUN pip install --upgrade pip wheel setuptools && pip install -r requirements.txt

COPY main_process ./main_process

WORKDIR ./main_process

EXPOSE 6666/tcp

CMD ["python" , "./main_process.py"]