version: '3'
services:
  main_process:
    build:
      context: .
      dockerfile: Dockerfile-main

    container_name: main_container

    depends_on:
      - mongoDB

    networks:
      - python-demo

  client_process:
    build:
      context: .
      dockerfile: Dockerfile-client

    container_name: client_container
    networks:
      - python-demo

    depends_on:
      - main_process

  mongoDB:
    container_name: mongoDB
    image: mongo
    volumes:
      - 'mongo:/data/db'
    ports:
      - '27017:27017'

    networks:
      - python-demo


volumes:
  mongo:

networks:
  python-demo:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24